
[functions.extract-pdf-text]
enabled = true
verify_jwt = true
import_map = "./functions/extract-pdf-text/deno.json"
entrypoint = "./functions/extract-pdf-text/index.ts"

[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
entrypoint = "./functions/stripe-webhook/index.ts"
